server:
  port: 8080
spring:
  kafka:
    producer:
      bootstrap-servers: 34.76.220.34:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      group-id: group_id
topic:
  name:
    producer: topic_qa
auto:
  create:
    topics:
      enable: true
